// Data Format: [Day(1=Fri, 2=Sat, 3=Sun), Venue, Screen, Time, Title, Details]
export const rawScheduleData = [
  // FRIDAY
  [1, "INOX MAISON", "1", "10:20 AM", "CIRCUSBOY", "German, Documentary, 86 min"],
  [1, "INOX MAISON", "1", "12:15 PM", "THE WHISPER", "Spanish, Horror, 100 min"],
  [1, "INOX MAISON", "1", "2:25 PM", "LONG STORY SHORT", "German, Dramedy, 107 min"],
  [1, "INOX MAISON", "1", "4:45 PM", "OUR HERO, BALTHAZAR", "English, Comedy-Drama, 91 min"],
  [1, "INOX MAISON", "1", "6:45 PM", "ELECTRIC MOON", "English, Adventure, Comedy, 103 min"],
  [1, "INOX MAISON", "1", "9:00 PM", "THE SOUFFLEUR", "English, Dramedy, 78 min"],
  [1, "INOX MAISON", "1", "10:45 PM", "Mermaid", "English, Horror, 105 min"],
  [1, "INOX MAISON", "2", "10:30 AM", "CLIMBING FOR LIFE", "Japanese, Adventure, 130 min"],
  [1, "INOX MAISON", "2", "1:00 PM", "DEDALUS", "Italian, Thriller, 92 min"],
  [1, "INOX MAISON", "2", "3:05 PM", "THE RICHEST WOMAN IN THE WORLD", "French, Drama, 121 min"],
  [1, "INOX MAISON", "2", "5:35 PM", "THE SUN RISES ON US ALL", "Mandarin, Drama, 133 min"],
  [1, "INOX MAISON", "2", "8:20 PM", "LEAVE ONE DAY", "French, Romance, 98 min"],
  [1, "INOX MAISON", "2", "10:30 PM", "THE RESIDENCE", "French, Thriller, 110 min"],
  [1, "INOX MAISON", "3", "10:00 AM", "AMRUM", "German, Drama, 93 min"],
  [1, "INOX MAISON", "3", "12:00 PM", "MUMBAI PUNE MUMBAI", "Marathi, Romance, Meet with Cast, 101 min"],
  [1, "INOX MAISON", "3", "4:35 PM", "TBC", ""],
  [1, "INOX MAISON", "3", "8:05 PM", "THIS TEMPTING MADNESS", "English, Thriller, 95 min"],
  [1, "INOX MAISON", "3", "10:55 PM", "RENTAL FAMILY", "English, Drama, 110 min"],
  [1, "INOX MAISON", "4", "10:25 AM", "REEDLAND", "Dutch, Drama, 105 min"],
  [1, "INOX MAISON", "4", "12:40 PM", "THE PRESIDENT'S CAKE", "Arabic, Drama, 105 min"],
  [1, "INOX MAISON", "4", "2:55 PM", "DIAMONDS ARE FOREVER", "English, Thriller, 120 min"],
  [1, "INOX MAISON", "4", "5:25 PM", "SIRĀT", "Spanish, Thriller, 115 min"],
  [1, "INOX MAISON", "4", "7:55 PM", "THE TESTAMENT OF ANN LEE", "English, Drama, 137 min"],
  [1, "INOX MAISON", "4", "10:45 PM", "NO OTHER CHOICE", "Korean, Thriller, 139 min"],
  [1, "INOX MAISON", "5", "10:35 AM", "THE REMNANTS OF YOU", "Spanish, Drama, 91 min"],
  [1, "INOX MAISON", "5", "12:35 PM", "SATYAKAM", "Hindi, Drama, 175 min"],
  [1, "INOX MAISON", "5", "5:30 PM", "SHIVA", "Hindi, Action, Meet with Director, 162 min"],
  [1, "INOX MAISON", "5", "9:40 PM", "ZIMMEDARI UMEED AZADI SANDYEEP", "Hindi, Thriller, 110 min"],
  [1, "INOX MAISON", "6", "10:05 AM", "SON OF SARA: VOLUME 1", "English, Horror, 85 min"],
  [1, "INOX MAISON", "6", "12:00 PM", "TBC", ""],
  [1, "INOX MAISON", "6", "3:00 PM", "IN WHICH ANNIE GIVES IT THOSE ONES", "English, 112 min, MEET THE DIRECTOR"],
  [1, "INOX MAISON", "6", "7:00 PM", "Opening Film to Be Announced Soon", ""],
  [1, "INOX MAISON", "6", "10:30 PM", "NO OTHER CHOICE", "Korean, Thriller, 139 min"],
  [1, "PVR ICON", "1", "12:50 PM", "THE PORTUGUESE HOUSE", "Spanish, Drama, 114 min"],
  [1, "PVR ICON", "1", "3:15 PM", "PEAK EVERYTHING", "French, Romance, 100 min"],
  [1, "PVR ICON", "1", "5:25 PM", "PIECES OF A FOREIGN LIFE", "French, Drama, 101 min"],
  [1, "PVR ICON", "1", "7:35 PM", "MEMENTO", "English, Thriller, 113 min"],
  [1, "PVR ICON", "1", "10:00 PM", "RESURRECTION", "Mandarin, Sci-Fi, 160 min"],
  [1, "PVR CITI MALL", "1", "10:55 AM", "HIDDEN MURDER", "Spanish, Thriller, 111 min"],
  [1, "PVR CITI MALL", "1", "1:15 PM", "TBC", ""],
  [1, "PVR CITI MALL", "1", "4:00 PM", "NINO", "French, Drama, 96 min"],
  [1, "PVR CITI MALL", "1", "6:05 PM", "THE REDEMPTION", "Spanish, Thriller, 115 min"],
  [1, "PVR CITI MALL", "1", "8:30 PM", "TBC", ""],
  [1, "PVR CITI MALL", "1", "10:30 PM", "WHISTLE", "English, Horror, 100 min"],
  [1, "CINÉPOLIS", "3", "11:50 AM", "HINT OF LOVE", "French, Romance, 90 min"],
  [1, "CINÉPOLIS", "3", "1:50 PM", "I'M NOT EVERYTHING I WANT TO BE", "Czech, Documentary, 90 min"],
  [1, "CINÉPOLIS", "3", "3:50 PM", "IT ALL ENDS HERE", "Croatian, Crime, 89 min"],
  [1, "CINÉPOLIS", "3", "5:50 PM", "DEAD OF WINTER", "English, Thriller, 98 min"],
  [1, "CINÉPOLIS", "3", "8:00 PM", "THE UGLY", "Korean, Thriller, 102 min"],
  [1, "CINÉPOLIS", "3", "10:15 PM", "BLOCKHEAD", "English, Thriller, 90 min"],
  [1, "CINÉPOLIS", "4", "10:20 AM", "A LUMINOUS LIFE", "Portuguese, Drama, 106 min"],
  [1, "CINÉPOLIS", "4", "12:30 PM", "REDUX REDUX", "English, Sci-Fi, 107 min"],
  [1, "CINÉPOLIS", "4", "2:50 PM", "BABY DOE", "English, Documentary, 100 min"],
  [1, "CINÉPOLIS", "4", "5:00 PM", "TBC", ""],
  [1, "CINÉPOLIS", "4", "7:40 PM", "SOFIA'S SUSPICION", "Spanish, Thriller, 100 min"],
  [1, "CINÉPOLIS", "4", "10:00 PM", "THE ARBORIST", "English, Thriller, 95 min"],
  [1, "PVR JUHU", "1", "12:55 PM", "THE ORPHANS", "French, Action, 95 min"],
  [1, "PVR JUHU", "1", "3:05 PM", "HEN", "Greek, Comedy, 96 min"],
  [1, "PVR JUHU", "1", "5:15 PM", "FANTASY LIFE", "English, Romance, 91 min"],
  [1, "PVR JUHU", "1", "7:15 PM", "TBC", ""],
  [1, "PVR JUHU", "1", "10:15 PM", "HAMNET", "English, Drama, 125 min"],
  [1, "PVR JUHU", "2", "1:15 PM", "A PALE VIEW OF HILLS", "Japanese, Drama, 123 min"],
  [1, "PVR JUHU", "2", "3:45 PM", "FURCY", "French, Drama, 108 min"],
  [1, "PVR JUHU", "2", "6:05 PM", "THE LOVE THAT REMAINS", "Icelandic, Drama, 109 min"],
  [1, "PVR JUHU", "2", "8:25 PM", "OLDBOY", "Korean, Thriller, 120 min"],
  [1, "PVR JUHU", "2", "10:30 PM", "SAFE HOUSE", "Norwegian, Thriller, 94 min"],

  // SATURDAY
  [2, "INOX MAISON", "1", "12:00 PM", "FIGHTER", "Norwegian, Documentary, 83 min"],
  [2, "INOX MAISON", "1", "2:00 PM", "THE LOVE THAT REMAINS", "Icelandic, Drama, 109 min"],
  [2, "INOX MAISON", "1", "4:20 PM", "BLOCKHEAD", "English, Thriller, 90 min"],
  [2, "INOX MAISON", "1", "6:20 PM", "PROJECT Y", "Korean, Crime, 110 min"],
  [2, "INOX MAISON", "1", "8:20 PM", "DEAD OF WINTER", "English, Thriller, 98 min"],
  [2, "INOX MAISON", "1", "11:00 PM", "DOLLY", "English, Horror, 82 min"],
  [2, "INOX MAISON", "2", "11:15 AM", "PIECES OF A FOREIGN LIFE", "French, Drama, 101 min"],
  [2, "INOX MAISON", "2", "1:20 PM", "PEAK EVERYTHING", "French, Romance, 100 min"],
  [2, "INOX MAISON", "2", "3:30 PM", "YOU FOUND ME", "French, Romance, 96 min"],
  [2, "INOX MAISON", "2", "5:30 PM", "COLOURS OF TIME", "French, Romance, 124 min"],
  [2, "INOX MAISON", "2", "10:45 PM", "CASE 137", "French, Thriller, 115 min"],
  [2, "INOX MAISON", "3", "1:00 PM", "TBC", ""],
  [2, "INOX MAISON", "3", "3:00 PM", "BHOOT", "Horror, Hindi, 113 min MEET THE DIRECTOR"],
  [2, "INOX MAISON", "3", "5:50 PM", "DEATH ON THE NILE", "English, Thriller, 127 min"],
  [2, "INOX MAISON", "3", "9:00 PM", "FANTASY LIFE", "English, Romance, 91 min"],
  [2, "INOX MAISON", "3", "11:00 PM", "IS THIS THING ON?", "English, Drama 124 min"],
  [2, "INOX MAISON", "4", "10:00 AM", "TBC", ""],
  [2, "INOX MAISON", "4", "12:40 PM", "A TALE OF TWO SISTERS", "Korean, Horror, 114 min"],
  [2, "INOX MAISON", "4", "3:05 PM", "A HAUNTING IN VENICE", "English, Thriller, 103 min"],
  [2, "INOX MAISON", "4", "5:20 PM", "ROMAN HOLIDAY", "English, Romance, 118 min"],
  [2, "INOX MAISON", "4", "7:50 PM", "SENTIMENTAL VALUE", "Norwegian, Drama, 133 min"],
  [2, "INOX MAISON", "4", "10:30 PM", "THE TESTAMENT OF ANN LEE", "English, Drama, 137 min"],
  [2, "INOX MAISON", "5", "9:25 AM", "RESURRECTION", "Mandarin, Sci-Fi 160 min"],
  [2, "INOX MAISON", "5", "12:15 PM", "LATE SHIFT", "German, Drama, 91 min"],
  [2, "INOX MAISON", "5", "2:15 PM", "THE LIGHT", "German, Sci-Fi, 162 min"],
  [2, "INOX MAISON", "5", "6:20 PM", "MASSEY SAHIB", "Hindi, Drama, 126 min MEET THE ACTOR"],
  [2, "INOX MAISON", "5", "10:45 PM", "HAMNET", "English, Drama, 125 min"],
  [2, "INOX MAISON", "6", "7:45 PM", "BAYAAN", "Hindi, Thriller, 120 min MEET THE CAST AND CREW"],
  [2, "INOX MAISON", "6", "11:15 PM", "LÉON: THE PROFESSIONAL", "French, Thriller, 130 min"],
  [2, "PVR ICON", "1", "1:10 PM", "THE SECRET FLOOR", "German, Family, 95 min"],
  [2, "PVR ICON", "1", "3:15 PM", "THE PRESIDENT'S CAKE", "Arabic, Drama, 105 min"],
  [2, "PVR ICON", "1", "5:30 PM", "VICKY CRISTINA BARCELONA", "English, Romance, 96 min"],
  [2, "PVR ICON", "1", "7:35 PM", "JAWS", "English, Adventure, 124 min"],
  [2, "PVR ICON", "1", "10:10 PM", "COUTURE", "French, Drama, 106 min"],
  [2, "PVR CITI MALL", "1", "12:35 PM", "CROSSING LINES", "Danish, Thriller, 103 min"],
  [2, "PVR CITI MALL", "1", "2:50 PM", "A TALE OF TWO SISTERS", "Korean, Drama, 114 min"],
  [2, "PVR CITI MALL", "1", "5:15 PM", "RANG DE BASANTI", "Hindi, Drama, 170 min"],
  [2, "PVR CITI MALL", "1", "8:35 PM", "NIGHT CREATURES", "Flemish, Thriller, 101 min"],
  [2, "PVR CITI MALL", "1", "10:45 PM", "THE TESTAMENT OF ANN LEE", "English, Drama, 137 min"],
  [2, "CINÉPOLIS", "3", "11:55 AM", "DISFORIA", "Spanish, Horror, 93 min"],
  [2, "CINÉPOLIS", "3", "1:55 PM", "SHIVA", "Hindi, Action, 162 min"],
  [2, "CINÉPOLIS", "3", "5:10 PM", "BARSAAT KI RAAT", "Hindi, Drama, 142 min"],
  [2, "CINÉPOLIS", "3", "8:10 PM", "THE BOTANIST", "Mandarin, Drama, 96 min"],
  [2, "CINÉPOLIS", "3", "10:15 PM", "I SAW THE DEVIL", "Korean, Thriller, 142 min"],
  [2, "CINÉPOLIS", "4", "11:55 AM", "BARREN LAND", "Spanish, Thriller, 101 min"],
  [2, "CINÉPOLIS", "4", "1:55 PM", "REEDLAND", "Dutch, Drama, 105 min"],
  [2, "CINÉPOLIS", "4", "4:10 PM", "THE SOUFFLEUR", "English, Drama, 78 min"],
  [2, "CINÉPOLIS", "4", "6:00 PM", "IN WHICH ANNIE GIVES IT THOSE ONES", "English, Comedy, 112 min"],
  [2, "CINÉPOLIS", "4", "8:20 PM", "THE WHISPER", "Horror, 100 min"],
  [2, "CINÉPOLIS", "4", "10:30 PM", "THE PORTUGUESE HOUSE", "Spanish, Thriller, 114 min"],
  [2, "PVR JUHU", "1", "11:20 AM", "TBC", ""],
  [2, "PVR JUHU", "1", "1:25 PM", "IS THIS THING ON?", "English, Drama, 124 min"],
  [2, "PVR JUHU", "1", "4:05 PM", "THE SOUND OF MUSIC", "English, Musical, 175 min"],
  [2, "PVR JUHU", "1", "7:25 PM", "NO OTHER CHOICE", "Korean, Thriller, 139 min"],
  [2, "PVR JUHU", "1", "10:15 PM", "RENTAL FAMILY", "English, Drama, 110 min"],
  [2, "PVR JUHU", "2", "10:30 AM", "NINO", "French, Drama, 96 min"],
  [2, "PVR JUHU", "2", "12:40 PM", "LÉON: THE PROFESSIONAL", "French, Thriller, 130 min"],
  [2, "PVR JUHU", "2", "3:20 PM", "WHEN HARRY MET SALLY", "English, Romance, 95 min"],
  [2, "PVR JUHU", "2", "5:25 PM", "TBC", ""],
  [2, "PVR JUHU", "2", "7:50 PM", "SENTIMENTAL VALUE", "Norwegian, Drama, 133 min"],
  [2, "PVR JUHU", "2", "10:30 PM", "SOUND OF FALLING", "German, Drama, 155 min"],

  // SUNDAY
  [3, "INOX MAISON", "1", "11:40 AM", "WARDRIVER", "English, Thriller, 90 min"],
  [3, "INOX MAISON", "1", "1:50 PM", "THE ARBORIST", "English, Thriller, 95 min"],
  [3, "INOX MAISON", "1", "4:00 PM", "THE BOTANIST", "Mandarin, Drama, 96 min"],
  [3, "INOX MAISON", "1", "6:10 PM", "CONTROL ROOM", "Spanish, Sci-Fi, 97 min"],
  [3, "INOX MAISON", "1", "8:40 PM", "SAFE HOUSE", "Norwegian, Thriller, 94 min"],
  [3, "INOX MAISON", "1", "10:45 PM", "DISFORIA", "Spanish, Horror, 93 min"],
  [3, "INOX MAISON", "2", "10:00 AM", "ANCESTRAL", "Spanish, Drama, 90 min"],
  [3, "INOX MAISON", "2", "12:00 PM", "I'M NOT EVERYTHING I WANT TO BE", "Documentary, Czech, 90 min"],
  [3, "INOX MAISON", "2", "2:00 PM", "WHISTLE", "English, Horror, 100 min"],
  [3, "INOX MAISON", "2", "4:10 PM", "THE PIANO ACCIDENT", "French, Comedy, 92 min"],
  [3, "INOX MAISON", "2", "6:10 PM", "THE ORPHANS", "French, Action, 95 min"],
  [3, "INOX MAISON", "2", "8:10 PM", "HIDDEN MURDER", "Spanish, Thriller, 111 min"],
  [3, "INOX MAISON", "2", "10:30 PM", "SOFIA'S SUSPICION", "Spanish, Thriller, 100 min"],
  [3, "INOX MAISON", "3", "11:00 AM", "RANG DE BASANTI", "Hindi, Drama, 170 min"],
  [3, "INOX MAISON", "3", "2:05 PM", "MEMENTO", "English, Thriller, 113 min"],
  [3, "INOX MAISON", "3", "4:30 PM", "TURTLE WALKER", "Hinglish, Documentary, 75 min"],
  [3, "INOX MAISON", "3", "7:30 PM", "COUTURE", "French, Drama, 106 min"],
  [3, "INOX MAISON", "3", "10:00 PM", "TBC", ""],
  [3, "INOX MAISON", "4", "10:05 AM", "REDUX REDUX", "English, Revenge Sci-Fi, 107 min"],
  [3, "INOX MAISON", "4", "12:25 PM", "HAMNET", "English, Drama, 125 min"],
  [3, "INOX MAISON", "4", "3:00 PM", "THE SOUND OF MUSIC", "English, Musical, 175 min"],
  [3, "INOX MAISON", "4", "6:20 PM", "WHEN HARRY MET SALLY", "English, Romance, 95 min"],
  [3, "INOX MAISON", "4", "8:25 PM", "RENTAL FAMILY", "English, Drama, 110 min"],
  [3, "INOX MAISON", "4", "10:45 PM", "I SAW THE DEVIL", "Korean, Drama, 142 min"],
  [3, "INOX MAISON", "5", "9:40 AM", "TBC", ""],
  [3, "INOX MAISON", "5", "12:30 PM", "TBC", "MEET THE DIRECTOR"],
  [3, "INOX MAISON", "5", "2:30 PM", "NIGHT CREATURES", "Flemish, Thriller, 101 min SRIRAM RAGHAVAN"],
  [3, "INOX MAISON", "5", "5:20 PM", "VICKY CRISTINA BARCELONA", "English, Romance, 96 min"],
  [3, "INOX MAISON", "5", "7:45 PM", "JAWS", "English, Adventure, 124 min"],
  [3, "INOX MAISON", "5", "10:20 PM", "SOUND OF FALLING", "German, Drama, 155 min"],
  [3, "INOX MAISON", "6", "11:00 AM", "BARSAAT KI RAAT", "Hindi, Drama, 142 min"],
  [3, "INOX MAISON", "6", "1:30 PM", "OLDBOY", "Korean, Thriller, 120 min"],
  [3, "INOX MAISON", "6", "4:00 PM", "TOH TI ANI FUJI", "Marathi, Romance, 135 min MEET THE CAST AND CREW"],
  [3, "INOX MAISON", "6", "9:00 PM", "Closing Film to Be Announced Soon", ""],
  [3, "PVR ICON", "1", "12:00 PM", "GADAR: EK PREM KATHA", "Hindi, Romance, 170 min"],
  [3, "PVR ICON", "1", "3:05 PM", "DIAMONDS ARE FOREVER", "English, Thriller, 120 min"],
  [3, "PVR ICON", "1", "5:35 PM", "LÉON: THE PROFESSIONAL", "French, Thriller, 130 min"],
  [3, "PVR ICON", "1", "8:15 PM", "BAYAAN", "Hindi, Thriller, 120 min"],
  [3, "PVR ICON", "1", "10:45 PM", "TBC", ""],
  [3, "PVR CITI MALL", "1", "10:40 AM", "WRANGLER", "Korean, Thriller, 107 min"],
  [3, "PVR CITI MALL", "1", "1:00 PM", "THE RESIDENCE", "French, Thriller, 110 min"],
  [3, "PVR CITI MALL", "1", "3:20 PM", "DOLLY", "English, Horror, 82 min"],
  [3, "PVR CITI MALL", "1", "5:20 PM", "CLIMBING FOR LIFE", "Japanese, Adventure, 130 min"],
  [3, "PVR CITI MALL", "1", "8:00 PM", "A PALE VIEW OF HILLS", "Japanese, Drama, 123 min"],
  [3, "PVR CITI MALL", "1", "10:30 PM", "SON OF SARA: VOL 1", "English, Horror, 85 min"],
  [3, "CINÉPOLIS", "3", "12:15 PM", "PROJECT Y", "Korean, Thriller, 110 min"],
  [3, "CINÉPOLIS", "3", "2:15 PM", "OLDBOY", "Korean, Thriller, 120 min"],
  [3, "CINÉPOLIS", "3", "4:45 PM", "TOH TI ANI FUJI", "Marathi, Romance, 135 min"],
  [3, "CINÉPOLIS", "3", "7:25 PM", "IS THIS THING ON?", "English, Drama, 124 min"],
  [3, "CINÉPOLIS", "3", "10:00 PM", "LONG STORY SHORT", "German, Dramedy, 107 min"],
  [3, "CINÉPOLIS", "4", "11:05 AM", "Mermaid", "English, Horror, 105 min"],
  [3, "CINÉPOLIS", "4", "1:05 PM", "IT ALL ENDS HERE", "Croatian, Crime, 89 min"],
  [3, "CINÉPOLIS", "4", "3:05 PM", "HEN", "Greek, Comedy, 96 min"],
  [3, "CINÉPOLIS", "4", "5:15 PM", "IRON HEART", "Russian, Adventure, 115 min"],
  [3, "CINÉPOLIS", "4", "7:45 PM", "AMRUM", "German, Drama, 93 min"],
  [3, "CINÉPOLIS", "4", "9:45 PM", "THE REMNANTS OF YOU", "Spanish, Drama, 91 min"],
  [3, "PVR JUHU", "1", "10:00 AM", "THE SUN RISES ON US ALL", "Mandarin, Drama, 133 min"],
  [3, "PVR JUHU", "1", "12:30 PM", "TBC", ""],
  [3, "PVR JUHU", "1", "3:00 PM", "THE LIGHT", "German, Sci-Fi, 162 min"],
  [3, "PVR JUHU", "1", "6:15 PM", "LATE SHIFT", "German, Drama, 91 min"],
  [3, "PVR JUHU", "1", "8:15 PM", "ROMAN HOLIDAY", "English, Romance, 118 min"],
  [3, "PVR JUHU", "1", "10:45 PM", "A TALE OF TWO SISTERS", "Korean, Horror, 114 min"],
  [3, "PVR JUHU", "2", "12:10 PM", "SIRĀT", "Spanish, Crime, 115 min"],
  [3, "PVR JUHU", "2", "2:40 PM", "THE UGLY", "Korean, Thriller, 102 min"],
  [3, "PVR JUHU", "2", "5:00 PM", "MEMENTO", "English, Thriller, 113 min"],
  [3, "PVR JUHU", "2", "7:20 PM", "THE TESTAMENT OF ANN LEE", "English, Drama, 137 min"]
];

export const daysMap = {
  1: "Friday, 13 March",
  2: "Saturday, 14 March",
  3: "Sunday, 15 March"
};

export const venuesList = Array.from(new Set(rawScheduleData.map(d => d[1])));
